In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("warehouse.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT NOT NULL,
    category TEXT,
    quantity INTEGER,
    price REAL
)
""")

conn.commit()

print("Database and table created successfully!")

Database and table created successfully!

In [3]:
def add_product(name, category, quantity, price):
    cursor.execute("""
    INSERT INTO products (product_name, category, quantity, price)
    VALUES (?, ?, ?, ?)
    """, (name, category, quantity, price))

    conn.commit()
    print("Product added successfully!")

In [4]:
add_product("Laptop", "Electronics", 10, 50000)
add_product("Mouse", "Electronics", 25, 500)
add_product("Keyboard", "Electronics", 15, 1200)

Product added successfully!
Product added successfully!
Product added successfully!

In [5]:
def view_inventory():
    df = pd.read_sql_query("SELECT * FROM products", conn)
    return df

view_inventory()

    product_id     product_name     category  quantity    price
0            1           Laptop  Electronics        20  50000.0
1            3         Keyboard  Electronics        15   1200.0
2            4           Laptop  Electronics        10  50000.0
3            5            Mouse  Electronics        25    500.0
4            6         Keyboard  Electronics        15   1200.0
5            7          Monitor  Electronics         8  12000.0
6            8          Printer  Electronics         5  15000.0
7            9     Office Chair    Furniture        12   4500.0
8           10      Office Desk    Furniture         7   8000.0
9           11        Bookshelf    Furniture         6   3500.0
10          12         Notebook   Stationery       100     50.0
11          13              Pen   Stationery       200     10.0
12          14           Marker   Stationery        80     25.0
13          15     Water Bottle    Utilities        40    300.0
14          16         LED Bulb    Utilities        60    150.0
15          17   Extension Cord    Utilities        20    450.0
16          18       Hard Drive  Electronics        18   5000.0
17          19  USB Flash Drive  Electronics        50    800.0
18          20           Webcam  Electronics        14   2500.0
19          21       Headphones  Electronics        22   1800.0
20          22           Router  Electronics         9   3500.0
21          23        Projector  Electronics         3  30000.0
22          24           Laptop  Electronics        10  50000.0
23          25            Mouse  Electronics        25    500.0
24          26         Keyboard  Electronics        15   1200.0
25          27           Laptop  Electronics        10  50000.0
26          28            Mouse  Electronics        25    500.0
27          29         Keyboard  Electronics        15   1200.0
28          30          Monitor  Electronics         8  12000.0
29          31          Printer  Electronics         5  15000.0
30          32     Office Chair    Furniture        12   4500.0
31          33      Office Desk    Furniture         7   8000.0
32          34        Bookshelf    Furniture         6   3500.0
33          35         Notebook   Stationery       100     50.0
34          36              Pen   Stationery       200     10.0
35          37           Marker   Stationery        80     25.0
36          38     Water Bottle    Utilities        40    300.0
37          39         LED Bulb    Utilities        60    150.0
38          40   Extension Cord    Utilities        20    450.0
39          41       Hard Drive  Electronics        18   5000.0
40          42  USB Flash Drive  Electronics        50    800.0
41          43           Webcam  Electronics        14   2500.0
42          44       Headphones  Electronics        22   1800.0
43          45           Router  Electronics         9   3500.0
44          46        Projector  Electronics         3  30000.0
45          47           Laptop  Electronics        10  50000.0
46          48            Mouse  Electronics        25    500.0
47          49         Keyboard  Electronics        15   1200.0

In [6]:
def search_product(product_name):
    query = """
    SELECT * FROM products
    WHERE product_name LIKE ?
    """
    
    df = pd.read_sql_query(query, conn,
                           params=(f"%{product_name}%",))
    return df

In [7]:
search_product("Laptop")

   product_id product_name     category  quantity    price
0           1       Laptop  Electronics        20  50000.0
1           4       Laptop  Electronics        10  50000.0
2          24       Laptop  Electronics        10  50000.0
3          27       Laptop  Electronics        10  50000.0
4          47       Laptop  Electronics        10  50000.0

In [8]:
def update_quantity(product_id, new_quantity):
    cursor.execute("""
    UPDATE products
    SET quantity = ?
    WHERE product_id = ?
    """, (new_quantity, product_id))

    conn.commit()
    print("Quantity updated successfully!")

In [9]:
update_quantity(1, 20)

Quantity updated successfully!

In [10]:
def delete_product(product_id):
    cursor.execute("""
    DELETE FROM products
    WHERE product_id = ?
    """, (product_id,))

    conn.commit()
    print("Product deleted successfully!")

In [11]:
delete_product(2)

Product deleted successfully!

In [12]:
def low_stock(threshold=5):
    query = """
    SELECT * FROM products
    WHERE quantity <= ?
    """

    df = pd.read_sql_query(query, conn,
                           params=(threshold,))
    return df

In [13]:
low_stock()

   product_id product_name     category  quantity    price
0           8      Printer  Electronics         5  15000.0
1          23    Projector  Electronics         3  30000.0
2          31      Printer  Electronics         5  15000.0
3          46    Projector  Electronics         3  30000.0

In [14]:
def inventory_report():
    total_products = cursor.execute("""
    SELECT COUNT(*) FROM products
    """).fetchone()[0]

    total_quantity = cursor.execute("""
    SELECT SUM(quantity) FROM products
    """).fetchone()[0]

    total_value = cursor.execute("""
    SELECT SUM(quantity * price) FROM products
    """).fetchone()[0]

    print("===== INVENTORY REPORT =====")
    print("Total Products:", total_products)
    print("Total Quantity:", total_quantity)
    print("Total Inventory Value: ₹", total_value)

In [15]:
inventory_report()

===== INVENTORY REPORT =====
Total Products: 48
Total Quantity: 1543
Total Inventory Value: ₹ 4474200.0

In [16]:
add_product("Laptop", "Electronics", 10, 50000)
add_product("Mouse", "Electronics", 25, 500)
add_product("Keyboard", "Electronics", 15, 1200)
add_product("Monitor", "Electronics", 8, 12000)
add_product("Printer", "Electronics", 5, 15000)

add_product("Office Chair", "Furniture", 12, 4500)
add_product("Office Desk", "Furniture", 7, 8000)
add_product("Bookshelf", "Furniture", 6, 3500)

add_product("Notebook", "Stationery", 100, 50)
add_product("Pen", "Stationery", 200, 10)
add_product("Marker", "Stationery", 80, 25)

add_product("Water Bottle", "Utilities", 40, 300)
add_product("LED Bulb", "Utilities", 60, 150)
add_product("Extension Cord", "Utilities", 20, 450)

add_product("Hard Drive", "Electronics", 18, 5000)
add_product("USB Flash Drive", "Electronics", 50, 800)
add_product("Webcam", "Electronics", 14, 2500)
add_product("Headphones", "Electronics", 22, 1800)
add_product("Router", "Electronics", 9, 3500)
add_product("Projector", "Electronics", 3, 30000)

Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!
Product added successfully!

In [17]:
view_inventory()

    product_id     product_name     category  quantity    price
0            1           Laptop  Electronics        20  50000.0
1            3         Keyboard  Electronics        15   1200.0
2            4           Laptop  Electronics        10  50000.0
3            5            Mouse  Electronics        25    500.0
4            6         Keyboard  Electronics        15   1200.0
..         ...              ...          ...       ...      ...
63          65  USB Flash Drive  Electronics        50    800.0
64          66           Webcam  Electronics        14   2500.0
65          67       Headphones  Electronics        22   1800.0
66          68           Router  Electronics         9   3500.0
67          69        Projector  Electronics         3  30000.0

[68 rows x 5 columns]

In [ ]:
while True:
    print("\n===== WAREHOUSE MANAGEMENT SYSTEM =====")
    print("1. Add Product")
    print("2. View Inventory")
    print("3. Search Product")
    print("4. Update Quantity")
    print("5. Delete Product")
    print("6. Low Stock Report")
    print("7. Inventory Report")
    print("8. Exit")

    choice = input("Enter your choice (1-8): ")

    if choice == "1":
        name = input("Product Name: ")
        category = input("Category: ")
        quantity = int(input("Quantity: "))
        price = float(input("Price: "))
        
        add_product(name, category, quantity, price)

    elif choice == "2":
        print(view_inventory())

    elif choice == "3":
        name = input("Enter product name to search: ")
        print(search_product(name))

    elif choice == "4":
        product_id = int(input("Enter Product ID: "))
        quantity = int(input("Enter New Quantity: "))
        
        update_quantity(product_id, quantity)

    elif choice == "5":
        product_id = int(input("Enter Product ID to delete: "))
        
        delete_product(product_id)

    elif choice == "6":
        threshold = int(input("Enter low stock threshold: "))
        print(low_stock(threshold))

    elif choice == "7":
        inventory_report()

    elif choice == "8":
        print("Exiting Warehouse Management System...")
        break

    else:
        print("Invalid choice! Please try again.")

===== WAREHOUSE MANAGEMENT SYSTEM =====
1. Add Product
2. View Inventory
3. Search Product
4. Update Quantity
5. Delete Product
6. Low Stock Report
7. Inventory Report
8. Exit